[tool.poetry]
name = "pyrabitthole"
version = "0.1.0"
description = ""
authors = ["itsOK"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
"web.py" = "^0.62"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
