data:
  - https://docs.diadata.org/
studies:
  - https://3boxlabs.com/
  - https://fortmatic.com/
  - https://magic.link/
  - https://github.com/bonedaddy
  - https://github.com/manifoldfinance/
  - https://github.com/madfish-solutions
  - https://github.com/sunnyRK
  - https://github.com/gelatodigital
  - https://github.com/zeriontech
  - https://github.com/yearn
  - https://github.com/consenlabs
  - https://github.com/complusnetwork
  - https://github.com/laminar-protocol
  - https://github.com/defiAnalysis/myswap-sdk
  - https://github.com/DecenterApps
  - https://github.com/hotswapfinance
  - https://github.com/definancer
  - https://github.com/philipdesmedt
  - https://github.com/bitfinexcom
  - https://github.com/creativetimofficial
  - https://www.stateofthedapps.com/zh
  - https://github.com/tenderly
  - https://github.com/walletlink/walletlink
  - https://github.com/project-serum/sol-wallet-adapter
  - https://www.xdaichain.com/for-users/get-xdai-tokens
  - https://docs.tokenbridge.net/
  - https://github.com/poanetwork
  - https://github.com/aragon/ui
  - https://github.com/DefiLlama/DefiLlama-Adapters
  