erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置
  redisSession: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: /opt/Pictures
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

ethServiceUrl: https://mainnet.infura.io/v3/xxx
orderServiceUrl: http://localhost:8080

compound:
  tmpFile: unhealthy_accounts.txt
  contractConfigFile: compound/mainnet.json
  infuraUrl: https://mainnet.infura.io/v3/xxxs
  #  infuraUrl: http://127.0.0.1:8545/
  wallet: /Users/Patrick/workspace/products/focus/defi-runner/keys/wallet-1.json
  pwd: password

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chain_alpha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mail:
    username: xxxxxx@qq.com
    password: 123456
    host: smtp.exmail.qq.com
    port: 465
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true